### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### Delete BusinessUnit by id
@business-unit-id = 
@business-unit-version = 

DELETE https://{{host}}/{{project-key}}/business-units/{{business-unit-id}}?version={{business-unit-version}}
&expand=
Authorization: Bearer {{ctp_access_token}}