### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### SetCustomField
@category-id = 
@category-version = 

POST https://api.{{host}}/{{project-key}}/categories/{{category-id}}
Authorization: Bearer {{ctp_access_token}}
Content-Type: application/json

    
    {
    "version": {{category-version}},
    "actions": [
        {
            "action" : "setCustomField",
            "name" : "ExampleStringTypeField",
            "value" : "TextString"
          }
    ]
}

