### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### SetLineItemSupplyChannel
@store-key = 
@cart-id = 
@cart-version = 
@lineItemId = 
@channel-id = 

POST https://{{host}}/{{project-key}}/in-store/key={{store-key}}/me/carts/{{cart-id}}
Authorization: Bearer {{ctp_access_token}}
Content-Type: application/json

    
    {
    "version": {{cart-version}},
    "actions": [
        {
            "action" : "setLineItemSupplyChannel",
            "lineItemId" : "{{lineItemId}}",
            "supplyChannel" : {
              "typeId" : "channel",
              "id" : "{{channel-id}}"
            }
          }
    ]
}

