### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### Delete my cart by id in store
@store-key = 
@cart-id = 
@cart-version = 

DELETE https://{{host}}/{{project-key}}/in-store/key={{store-key}}/me/carts/{{cart-id}}
#?version={{cart-version}}
#&expand=
Authorization: Bearer {{ctp_access_token}}