### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### Change a customers password

POST https://api.{{host}}/{{project-key}}/customers/password
Authorization: Bearer {{ctp_access_token}}

{
  "id" : "3cdcdcc8-80c5-41bb-abb5-ac8772c9cc24",
  "version" : 1,
  "currentPassword" : "secret123",
  "newPassword" : "newSecret456"
}