### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### get ByProjectKeyImportContainers

GET https://import.{{host}}/{{project-key}}/import-containers
#?limit=
#&offset=
#&sort=
Authorization: Bearer {{ctp_access_token}}
