### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### Check shipping-methods are existing

HEAD https://api.{{host}}/{{project-key}}/shipping-methods
#?where=
Authorization: Bearer {{ctp_access_token}}
