### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### Get ShippingMethods for a cart and location

GET https://{{host}}/{{project-key}}/shipping-methods/matching-cart-location?country=
&state=
&cartId=
&expand=
Authorization: Bearer {{ctp_access_token}}