### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### Create InventoryEntry

POST https://{{host}}/{{project-key}}/inventory
#?expand=
Authorization: Bearer {{ctp_access_token}}{
  "sku" : "sku_GIRLS_CREW_variant1_1421832124541",
  "quantityOnStock" : 4,
  "availableQuantity" : 4
}