### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### Get matching product discounts

POST https://{{host}}/{{project-key}}/product-discounts/matching
Authorization: Bearer {{ctp_access_token}}

{
  "productId": "123456",
  "variantId": 1,
  "staged": false,
  "price": {
    "value": {
      "centAmount": 100,
      "currencyCode": "EUR"
    }
  }
}
