### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### SetAssociates
@associate-id = 
@business-unit-id = 

POST https://{{host}}/{{project-key}}/as-associate/{{associate-id}}/business-units/{{business-unit-id}}
#?expand=
Authorization: Bearer {{ctp_access_token}}{
    "version": {{business-unit-version}},
    "actions": [
        {
            "action" : "setAssociates",
            "associates" : [ {
              "customer" : {
                "typeId" : "customer",
                "id" : "some-customer-id"
              },
              "associateRoleAssignments" : [ {
                "associateRole" : {
                  "typeId" : "associate-role",
                  "key" : "admin"
                },
                "inheritance" : "Enabled"
              } ]
            }, {
              "customer" : {
                "typeId" : "customer",
                "id" : "another-customer-id"
              },
              "associateRoleAssignments" : [ {
                "associateRole" : {
                  "typeId" : "associate-role",
                  "key" : "buyer"
                }
              } ]
            } ]
          }
    ]
}