### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### Create TaxCategory

POST https://api.{{host}}/{{project-key}}/tax-categories
#?expand=
Authorization: Bearer {{ctp_access_token}}

{
  "name" : "test-tax-category",
  "rates" : [ {
    "name" : "HST Ontario",
    "amount" : 0.13,
    "includedInPrice" : true,
    "country" : "CA",
    "state" : "ON",
    "subRates" : [ {
      "name" : "Federal rate (GST 5%)",
      "amount" : 0.05
    }, {
      "name" : "Provincial rate (PST 8%)",
      "amount" : 0.08
    } ]
  } ]
}