### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### Delete TaxCategory by id
@tax-category-id = 
@tax-category-version = 

DELETE https://{{host}}/{{project-key}}/tax-categories/{{tax-category-id}}
#?version={{tax-category-version}}
#&expand=
Authorization: Bearer {{ctp_access_token}}