### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### AddAttributeDefinition
@product-type-id = 
@product-type-version = 

POST https://{{host}}/{{project-key}}/product-types/{{product-type-id}}
Authorization: Bearer {{ctp_access_token}}
Content-Type: application/json

    
    {
    "version": {{product-type-version}},
    "actions": [
        {
            "action" : "addAttributeDefinition",
            "attribute" : {
              "type" : {
                "name" : "text"
              },
              "name" : "your-attribute-name",
              "label" : {
                "en" : "English label",
                "de" : "German label"
              },
              "isRequired" : false,
              "attributeConstraint" : "None",
              "inputTip" : {
                "en" : "English input tip",
                "de" : "German input tip"
              },
              "inputHint" : "SingleLine",
              "isSearchable" : true
            }
          }
    ]
}

