### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### ChangePlainEnumValueLabel
@product-type-id = 
@product-type-version = 

POST https://{{host}}/{{project-key}}/product-types/{{product-type-id}}
Authorization: Bearer {{ctp_access_token}}
Content-Type: application/json

    
    {
    "version": {{product-type-version}},
    "actions": [
        {
            "action" : "changePlainEnumValueLabel",
            "attributeName" : "your-attribute-name",
            "newValue" : {
              "key" : "existing enum key",
              "label" : "new label for this enum"
            }
          }
    ]
}

