### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### SetInputTip
@product-type-id = 
@product-type-version = 

POST https://api.{{host}}/{{project-key}}/product-types/{{product-type-id}}
Authorization: Bearer {{ctp_access_token}}
Content-Type: application/json

    
    {
    "version": {{product-type-version}},
    "actions": [
        {
            "action" : "setInputTip",
            "attributeName" : "your-attribute-name",
            "inputTip" : {
              "en" : "New English input tip",
              "de" : "New German input tip"
            }
          }
    ]
}

