### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### SetDescription
@product-tailoring-id = 
@product-tailoring-version = 

POST https://{{host}}/{{project-key}}/product-tailoring/{{product-tailoring-id}}
Authorization: Bearer {{ctp_access_token}}
Content-Type: application/json

    
    {
    "version": {{product-tailoring-version}},
    "actions": [
        {
            "action" : "setDescription",
            "description" : {
              "en" : "A description"
            },
            "staged" : true
          }
    ]
}

