### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### Get Quote by id
@associate-id = 
@business-unit-key = 
@quote-id = 

GET https://{{host}}/{{project-key}}/as-associate/{{associate-id}}/in-business-unit/key={{business-unit-key}}/quotes/{{quote-id}}
#?expand=
Authorization: Bearer {{ctp_access_token}}