### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### Gets the current or staged representation of a Product Tailoring by its Product key from a specific Store
@store-key = 
@product-key = 

GET https://api.{{host}}/{{project-key}}/in-store/key={{store-key}}/products/key={{product-key}}/product-tailoring
#?expand=
Authorization: Bearer {{ctp_access_token}}
