### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### Delete ProductType by key
@product-type-key = 
@product-type-version = 

DELETE https://{{host}}/{{project-key}}/product-types/key={{product-type-key}}
#?version={{product-type-version}}
#&expand=
Authorization: Bearer {{ctp_access_token}}