### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### Get ProductType by key
@product-type-key = 

GET https://api.{{host}}/{{project-key}}/product-types/key={{product-type-key}}
#?expand=
Authorization: Bearer {{ctp_access_token}}
