### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### RequestQuoteRenegotiation
@quote-id = 
@quote-version = 

POST https://{{host}}/{{project-key}}/quotes/{{quote-id}}
Authorization: Bearer {{ctp_access_token}}
Content-Type: application/json

    
    {
    "version": {{quote-version}},
    "actions": [
        {
            "action" : "requestQuoteRenegotiation",
            "buyerComment" : "Please also give me a 10% discount on the red T-shirts."
          }
    ]
}

