### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### SetAttributes
@attribute-group-id = 
@attribute-group-version = 

POST https://{{host}}/{{project-key}}/attribute-groups/{{attribute-group-id}}
Authorization: Bearer {{ctp_access_token}}
Content-Type: application/json

    
    {
    "version": {{attribute-group-version}},
    "actions": [
        {
            "action" : "setAttributes",
            "attributes" : [ {
              "key" : "a1"
            }, {
              "key" : "a2"
            } ]
          }
    ]
}

