### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### Delete Subscription by key
@subscription-key = 

DELETE https://{{host}}/{{project-key}}/subscriptions/key={{subscription-key}}
#?version={{subscription-version}}
Authorization: Bearer {{ctp_access_token}}
