### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### Upload a Product image
@product-id = 

POST https://{{host}}/{{project-key}}/products/{{product-id}}/images
#?filename=
#&variant=
#&sku=
#&staged=
Authorization: Bearer {{ctp_access_token}}