### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### Get Deployment by id
@deployment-id = 

GET https://connect.{{host}}/{{project-key}}/deployments/{{deployment-id}}
Authorization: Bearer {{ctp_access_token}}
