### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### AddAddress
@business-unit-id = 
@business-unit-version = 

POST https://api.{{host}}/{{project-key}}/business-units/{{business-unit-id}}
Authorization: Bearer {{ctp_access_token}}
Content-Type: application/json

    
    {
    "version": {{business-unit-version}},
    "actions": [
        {
            "action" : "addAddress",
            "address" : {
              "id" : "exampleAddress",
              "key" : "exampleKey",
              "title" : "My Address",
              "salutation" : "Mr.",
              "firstName" : "Example",
              "lastName" : "Person",
              "streetName" : "Example Street",
              "streetNumber" : "4711",
              "additionalStreetInfo" : "Backhouse",
              "postalCode" : "80933",
              "city" : "Exemplary City",
              "region" : "Exemplary Region",
              "state" : "Exemplary State",
              "country" : "DE",
              "company" : "My Company Name",
              "department" : "Sales",
              "building" : "Hightower 1",
              "apartment" : "247",
              "pOBox" : "2471",
              "phone" : "+49 89 12345678",
              "mobile" : "+49 171 2345678",
              "email" : "mail@example.com",
              "fax" : "+49 89 12345679",
              "additionalAddressInfo" : "no additional Info",
              "externalId" : "Information not needed"
            }
          }
    ]
}

