### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### Import import-container
@import-container-key = 

POST https://{{host}}/{{project-key}}/types/import-containers/{{import-container-key}}
Authorization: Bearer {{ctp_access_token}}

{
  "type" : "type",
  "resources" : [ {
    "key" : "type-key",
    "name" : {
      "en" : "Name of type"
    },
    "description" : {
      "en" : "Description of type"
    },
    "resourceTypeIds" : [ "customer" ],
    "fieldDefinitions" : [ {
      "type" : {
        "name" : "String"
      },
      "name" : "string-type-name",
      "label" : {
        "en" : "A label for the string field."
      },
      "required" : false,
      "inputHint" : "SingleLine"
    } ]
  } ]
}