### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### Import import-container
@import-container-key = 

POST https://{{host}}/{{project-key}}/discount-codes/import-containers/{{import-container-key}}
Authorization: Bearer {{ctp_access_token}}

{
  "type" : "discount-code",
  "resources" : [ {
    "key" : "discountCodeKey",
    "code" : "Save10",
    "name" : {
      "en" : "Save10"
    },
    "cartDiscounts" : [ {
      "typeId" : "cart-discount",
      "key" : "cartDiscountKey"
    } ],
    "isActive" : false,
    "groups" : [ ]
  } ]
}