### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### Get CustomObjectPagedQueryResponse by container
@container = 

GET https://{{host}}/{{project-key}}/custom-objects/{{container}}?sort=
&where=
&expand=
&/^var[.][a-zA-Z0-9]+$/=
&limit=
&offset=
&withTotal=
Authorization: Bearer {{ctp_access_token}}