### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### ChangeName
@product-id = 
@product-version = 

POST https://api.{{host}}/{{project-key}}/products/{{product-id}}
Authorization: Bearer {{ctp_access_token}}
Content-Type: application/json

    
    {
    "version": {{product-version}},
    "actions": [
        {
            "action" : "changeName",
            "name" : {
              "de" : "Mein neuer Produkt Name",
              "en" : "My new product name"
            }
          }
    ]
}

