### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### SetPrices
@product-id = 
@product-version = 

POST https://api.{{host}}/{{project-key}}/products/{{product-id}}
Authorization: Bearer {{ctp_access_token}}
Content-Type: application/json

    
    {
    "version": {{product-version}},
    "actions": [
        {
            "action" : "setPrices",
            "variantId" : 1,
            "prices" : [ {
              "value" : {
                "currencyCode" : "USD",
                "centAmount" : 3100
              }
            }, {
              "value" : {
                "currencyCode" : "EUR",
                "centAmount" : 4000
              }
            } ]
          }
    ]
}

