### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### Create State

POST https://{{host}}/{{project-key}}/states
#?expand=
Authorization: Bearer {{ctp_access_token}}

{
  "key" : "test-state",
  "type" : "ProductState",
  "roles" : [ ],
  "initial" : true
}