### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### Get State by id
@state-id = 

GET https://{{host}}/{{project-key}}/states/{{state-id}}
#?expand=
Authorization: Bearer {{ctp_access_token}}
