### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### SetItemShippingAddressCustomType
@order-id = 
@order-version = 
@address-key = 
@type-id = 

POST https://{{host}}/{{project-key}}/orders/{{order-id}}
Authorization: Bearer {{ctp_access_token}}
Content-Type: application/json

    
    {
    "version": {{order-version}},
    "actions": [
        {
            "action" : "setItemShippingAddressCustomType",
            "addressKey" : "{{address-key}}",
            "type" : {
              "id" : "{{type-id}}",
              "typeId" : "type"
            },
            "fields" : {
              "exampleStringTypeField" : "TextString"
            }
          }
    ]
}

