### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### ChangePredicate
@product-discount-id = 
@product-discount-version = 
@product-id = 

POST https://api.{{host}}/{{project-key}}/product-discounts/{{product-discount-id}}
Authorization: Bearer {{ctp_access_token}}
Content-Type: application/json

    
    {
    "version": {{product-discount-version}},
    "actions": [
        {
            "action" : "changePredicate",
            "predicate" : "product.id = "{{product-id}}""
          }
    ]
}

