### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### Check shopping-lists are existing
@store-key = 

HEAD https://{{host}}/{{project-key}}/in-store/key={{store-key}}/me/shopping-lists
#?where=
Authorization: Bearer {{ctp_access_token}}
