### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### AddCustomShippingMethod
@associate-id = 
@business-unit-key = 
@cart-id = 
@cart-version = 
@tax-category-id = 

POST https://{{host}}/{{project-key}}/as-associate/{{associate-id}}/in-business-unit/key={{business-unit-key}}/carts/{{cart-id}}
Authorization: Bearer {{ctp_access_token}}
Content-Type: application/json

    
    {
    "version": {{cart-version}},
    "actions": [
        {
            "action" : "addCustomShippingMethod",
            "shippingKey" : "shippingMethodKey1",
            "shippingMethodName" : "oneOfCustomShippingMethods",
            "shippingAddress" : {
              "key" : "exampleKey",
              "streetName" : "Example Street",
              "streetNumber" : "4711",
              "postalCode" : "80933",
              "city" : "Exemplary City",
              "region" : "Exemplary Region",
              "state" : "Exemplary State",
              "country" : "DE"
            },
            "shippingRate" : {
              "price" : {
                "currencyCode" : "EUR",
                "centAmount" : 4200
              }
            },
            "taxCategory" : {
              "id" : "{{tax-category-id}}",
              "typeId" : "tax-category"
            },
            "deliveries" : [ ]
          }
    ]
}

