### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### RemoveBillingAddressId
@customer-id = 
@customer-version = 
@addressId = 

POST https://api.{{host}}/{{project-key}}/customers/{{customer-id}}
Authorization: Bearer {{ctp_access_token}}
Content-Type: application/json

    
    {
    "version": {{customer-version}},
    "actions": [
        {
            "action" : "removeBillingAddressId",
            "addressId" : "{{addressId}}"
          }
    ]
}

