### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### Query customer-groups

GET https://{{host}}/{{project-key}}/customer-groups
#?where=
#&expand=
#&sort=
#&limit=
#&offset=
#&withTotal=
#&/^var[.][a-zA-Z0-9]+$/=
Authorization: Bearer {{ctp_access_token}}
