### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### SetSellerComment
@staged-quote-id = 
@staged-quote-version = 

POST https://{{host}}/{{project-key}}/staged-quotes/{{staged-quote-id}}
Authorization: Bearer {{ctp_access_token}}
Content-Type: application/json

    
    {
    "version": {{staged-quote-version}},
    "actions": [
        {
            "action" : "setSellerComment",
            "sellerComment" : "Please let me know if this matches your expectations"
          }
    ]
}

