### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### SetCustomShippingMethod
@cart-id = 
@cart-version = 
@tax-category-id = 

POST https://{{host}}/{{project-key}}/carts/{{cart-id}}
Authorization: Bearer {{ctp_access_token}}
Content-Type: application/json

    
    {
    "version": {{cart-version}},
    "actions": [
        {
            "action" : "setCustomShippingMethod",
            "shippingMethodName" : "myCustomShippingMethod",
            "shippingRate" : {
              "price" : {
                "currencyCode" : "EUR",
                "centAmount" : 4200
              }
            },
            "taxCategory" : {
              "id" : "{{tax-category-id}}",
              "typeId" : "tax-category"
            }
          }
    ]
}

