### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### SetCustomLineItemShippingDetails
@cart-id = 
@cart-version = 
@customlineItemId = 
@addressKey = 

POST https://api.{{host}}/{{project-key}}/carts/{{cart-id}}
Authorization: Bearer {{ctp_access_token}}
Content-Type: application/json

    
    {
    "version": {{cart-version}},
    "actions": [
        {
            "action" : "setCustomLineItemShippingDetails",
            "customLineItemId" : "{{customlineItemId}}",
            "shippingDetails" : {
              "targets" : [ {
                "addressKey" : "{{addressKey}}",
                "quantity" : 1
              } ]
            }
          }
    ]
}

