### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### TransitionState
@review-id = 
@review-version = 
@state-id = 

POST https://{{host}}/{{project-key}}/reviews/{{review-id}}
Authorization: Bearer {{ctp_access_token}}
Content-Type: application/json

    
    {
    "version": {{review-version}},
    "actions": [
        {
            "action" : "transitionState",
            "state" : {
              "typeId" : "state",
              "id" : "{{state-id}}"
            }
          }
    ]
}

