### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### SetDescription
@shopping-list-id = 

POST https://{{host}}/{{project-key}}/me/shopping-lists/{{shopping-list-id}}?expand=
Authorization: Bearer {{ctp_access_token}}{
    "version": {{shopping-list-version}},
    "actions": [
        {
            "action" : "setDescription",
            "description" : {
              "en" : "New description",
              "de" : "Neue Beschreibung"
            }
          }
    ]
}