### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### SetShippingMethod
@cart-id = 
@cart-version = 
@shipping-method-id = 

POST https://api.{{host}}/{{project-key}}/me/carts/{{cart-id}}
#?expand=
Authorization: Bearer {{ctp_access_token}}

{
    "version": {{cart-version}},
    "actions": [
        {
            "action" : "setShippingMethod",
            "shippingMethod" : {
              "id" : "{{shipping-method-id}}",
              "typeId" : "shipping-method"
            }
          }
    ]
}