### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### Get ConnectorDraft by key
@draft-key = 

GET https://connect.{{host}}/connectors/drafts/key={{draft-key}}
Authorization: Bearer {{ctp_access_token}}
