### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### Get ProductProjection by key
@product-projection-key = 

GET https://{{host}}/{{project-key}}/product-projections/key={{product-projection-key}}?staged=
&priceCurrency=
&priceCountry=
&priceCustomerGroup=
&priceChannel=
&localeProjection=
&storeProjection=
&expand=
Authorization: Bearer {{ctp_access_token}}