### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### Search Products by get

GET https://{{host}}/{{project-key}}/product-projections/search
#?fuzzy=
#&fuzzyLevel=
#&markMatchingVariants=
#&filter=
#&filter.facets=
#&filter.query=
#&facet=
#&/text.[a-z]{2}(-[A-Z]{2})?/=
#&sort=
#&limit=
#&offset=
#&withTotal=
#&staged=
#&priceCurrency=
#&priceCountry=
#&priceCustomerGroup=
#&priceChannel=
#&localeProjection=
#&storeProjection=
#&expand=
Authorization: Bearer {{ctp_access_token}}