### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### SetItemShippingAddressCustomField
@associate-id = 
@business-unit-key = 
@order-id = 
@order-version = 
@address-key = 

POST https://api.{{host}}/{{project-key}}/as-associate/{{associate-id}}/in-business-unit/key={{business-unit-key}}/orders/{{order-id}}
Authorization: Bearer {{ctp_access_token}}
Content-Type: application/json

    
    {
    "version": {{order-version}},
    "actions": [
        {
            "action" : "setItemShippingAddressCustomField",
            "addressKey" : "{{address-key}}",
            "name" : "ExampleStringTypeField",
            "value" : "TextString"
          }
    ]
}

