### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### Delete Type by id
@type-id = 
@type-version = 

DELETE https://{{host}}/{{project-key}}/types/{{type-id}}?version={{type-version}}
&expand=
Authorization: Bearer {{ctp_access_token}}