### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### Delete Type by key
@type-key = 
@type-version = 

DELETE https://{{host}}/{{project-key}}/types/key={{type-key}}
#?version={{type-version}}
#&expand=
Authorization: Bearer {{ctp_access_token}}
