### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### Delete Category by id
@category-id = 

DELETE https://{{host}}/{{project-key}}/categories/{{category-id}}
#?version={{category-version}}
#&expand=
Authorization: Bearer {{ctp_access_token}}
