### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### Get Category by key
@category-key = 

GET https://{{host}}/{{project-key}}/categories/key={{category-key}}?expand=
Authorization: Bearer {{ctp_access_token}}