### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### ChangeKey
@state-id = 
@state-version = 

POST https://{{host}}/{{project-key}}/states/{{state-id}}
Authorization: Bearer {{ctp_access_token}}
Content-Type: application/json

    
    {
    "version": {{state-version}},
    "actions": [
        {
            "action" : "changeKey",
            "key" : "ChangedStateKey"
          }
    ]
}

