### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### ImportCustomLineItemState
@store-key = 
@order-id = 
@order-version = 
@customLineItemId = 
@state-id = 

POST https://api.{{host}}/{{project-key}}/in-store/key={{store-key}}/orders/{{order-id}}
#?expand=
Authorization: Bearer {{ctp_access_token}}

{
    "version": {{order-version}},
    "actions": [
        {
            "action" : "importCustomLineItemState",
            "customLineItemId" : "{{customLineItemId}}",
            "state" : [ {
              "quantity" : 6,
              "state" : {
                "typeId" : "state",
                "id" : "{{state-id}}"
              }
            } ]
          }
    ]
}