### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### RemoveLineItem
@store-key = 
@cart-id = 

POST https://{{host}}/{{project-key}}/in-store/key={{store-key}}/carts/{{cart-id}}?expand=
Authorization: Bearer {{ctp_access_token}}{
    "version": {{cart-version}},
    "actions": [
        {
            "action" : "removeLineItem",
            "lineItemId" : "{{lineItemId}}",
            "quantity" : 1,
            "externalPrice" : {
              "currencyCode" : "EUR",
              "centAmount" : 4000
            },
            "shippingDetailsToRemove" : {
              "targets" : [ {
                "addressKey" : "AddressKeyStringFromAddress",
                "quantity" : 2
              } ]
            }
          }
    ]
}