### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### SetDeliveryAddressCustomType
@store-key = 
@order-id = 

POST https://{{host}}/{{project-key}}/in-store/key={{store-key}}/orders/{{order-id}}
#?expand=
Authorization: Bearer {{ctp_access_token}}

{
    "version": {{order-version}},
    "actions": [
        {
            "action" : "setDeliveryAddressCustomType",
            "deliveryId" : "{{delivery-id}}",
            "type" : {
              "id" : "{{type-id}}",
              "typeId" : "type"
            },
            "fields" : {
              "exampleStringTypeField" : "TextString"
            }
          }
    ]
}