### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### SetItemShippingAddressCustomField
@store-key = 
@order-id = 
@order-version = 
@address-key = 

POST https://{{host}}/{{project-key}}/in-store/key={{store-key}}/orders/{{order-id}}
#?expand=
Authorization: Bearer {{ctp_access_token}}

{
    "version": {{order-version}},
    "actions": [
        {
            "action" : "setItemShippingAddressCustomField",
            "addressKey" : "{{address-key}}",
            "name" : "ExampleStringTypeField",
            "value" : "TextString"
          }
    ]
}