### Authentication
    # @name auth
    POST https://{{client_id}}:{{client_secret}}@{{auth_url}}/oauth/token?grant_type=client_credentials&scope={{scopes}}
    
    @ctp_access_token = {{auth.response.body.access_token}}

### SetReturnInfo
@store-key = 
@order-id = 

POST https://{{host}}/{{project-key}}/in-store/key={{store-key}}/orders/{{order-id}}?expand=
Authorization: Bearer {{ctp_access_token}}{
    "version": {{order-version}},
    "actions": [
        {
            "action" : "setReturnInfo",
            "items" : [ {
              "items" : [ {
                "quantity" : 1,
                "lineItemId" : "{{lineItemId}}",
                "comment" : "any comment",
                "shipmentState" : "Returned"
              } ],
              "returnTrackingId" : "returnTrackingId-example",
              "returnDate" : "2021-04-30T09:21:15.003Z"
            } ]
          }
    ]
}